"""add compliance verification

Revision ID: 448347671d83
Revises: e6c605f0a8ef
Create Date: 2026-09-09 21:44:04.470952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448347671d83'
down_revision: Union[str, Sequence[str], None] = 'e6c605f0a8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_verifications_id'), 'compliance_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_verifications_inspection_id'), 'compliance_verifications', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_compliance_verifications_officer_id'), 'compliance_verifications', ['officer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_verifications_officer_id'), table_name='compliance_verifications')
    op.drop_index(op.f('ix_compliance_verifications_inspection_id'), table_name='compliance_verifications')
    op.drop_index(op.f('ix_compliance_verifications_id'), table_name='compliance_verifications')
    op.drop_table('compliance_verifications')
    # ### end Alembic commands ###
