"""add scan ocr declaration tables

Revision ID: e6c605f0a8ef
Revises: ce16cced4b33
Create Date: 2026-09-09 09:44:46.199563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c605f0a8ef'
down_revision: Union[str, Sequence[str], None] = 'ce16cced4b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('scan_type', sa.String(length=30), server_default='full', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('pipeline_version', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['inspection_images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_image_id'), 'scans', ['image_id'], unique=False)
    op.create_index(op.f('ix_scans_inspection_id'), 'scans', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_scans_scan_type'), 'scans', ['scan_type'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.String(length=255), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['inspection_images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declarations_field_name'), 'declarations', ['field_name'], unique=False)
    op.create_index(op.f('ix_declarations_image_id'), 'declarations', ['image_id'], unique=False)
    op.create_index(op.f('ix_declarations_inspection_id'), 'declarations', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_declarations_scan_id'), 'declarations', ['scan_id'], unique=False)
    op.create_table('ocr_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=100), nullable=False),
    sa.Column('engine_version', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=30), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_results_scan_id'), 'ocr_results', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_results_scan_id'), table_name='ocr_results')
    op.drop_table('ocr_results')
    op.drop_index(op.f('ix_declarations_scan_id'), table_name='declarations')
    op.drop_index(op.f('ix_declarations_inspection_id'), table_name='declarations')
    op.drop_index(op.f('ix_declarations_image_id'), table_name='declarations')
    op.drop_index(op.f('ix_declarations_field_name'), table_name='declarations')
    op.drop_table('declarations')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_scan_type'), table_name='scans')
    op.drop_index(op.f('ix_scans_inspection_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_image_id'), table_name='scans')
    op.drop_table('scans')
    # ### end Alembic commands ###
